variables:
# variable de grupo de artifactory
- group: Artifactory  
# variable de grupos de fluid
- group: Fluid  
# Propiedad del sonarQube para indicar el directorio a analizar
- name: sonarSources
  value: 'src' 
# propiedad de sonarQube para indicar los directorios a excluir en el análisis
- name: sonarExclusions
  value: 'node_modules/**, /**/*.module.ts,/src/environments/*,/src/assets/*,**/*.spec.ts,/,/src/assets/*,**/*.config.ts'
# propiedad de sonarQube para indicar el directorio donde se encontrara el reporte de cobertura
- name: sonarCoveragePaths 
  value: 'coverage/lcov.info' 
# 1=proyecto nuevo en sonarQube y 0=para actualizar una rama nueva del proyecto existente en sonarQube
- name: sonarCreateMaster
  value: '1'  
# Nombre del service connection para tarea de sonarQube
- name: sonarQubeServiceEndpoint 
  value: 'SonarLts' 
# Nombre del service connection de sonarQube para tarea de gradle o maven
- name: sonarQubeServiceEndpointGeneric
  value: 'Sonar-Generic-Lts' 
# nombre del script de compilación
- name: commandBuild
  value: 'build'  
# nombre del script de pruebas unitarias
- name: unitTestCommand
  value: 'test' 
# js= javascript y tsc= typescript
- name: appType
  value: '' 
# versión que se descargará en el agente temporalmente, si no se agrega valor utiliza la versión por defecto del agente
- name: versionNode
  value: '' 
# id de proyecto en fluid asserts. Preguntar al lider del componente o lider técnico el valor
- name: idfluid
  value: $(id) 
# secretKey de proyecto en fluid asserts. Preguntar al lider del componente o lider técnico el valor
- name: secretfluid
  value: $(secret)
# variable para localizar package.json de projecto widget, de no ser el caso dejarla vacía
- name: packageWorkingDir
  value: ''

resources:
  repositories:
    - repository: template
      type: git
      name: DevOps/_git/templates-yaml
      ref: 'refs/heads/master' # indicamos la rama que apuntamos en el repositorios template-yaml, siempre debemos apuntar a master
trigger:
  - master
  - develop
  - release
  - release/*

name: $(date:yyyyMMdd)$(rev:.r)
stages:
- stage:
  jobs:
  - job:
    pool:
      name: Banistmo-Linux-Pool
    workspace:
      clean: resources
    steps:
    - template: build_NJS_LTS.yml@template #ref de template en otro repository
      parameters:
        sonarCoveragePaths: ${{variables.sonarCoveragePaths}}
        sonarExclusions: ${{variables.sonarExclusions}}
        sonarSources: ${{variables.sonarSources}}
        sonarCreateMaster: ${{variables.sonarCreateMaster}}
        sonarQubeServiceEndpoint: ${{variables.sonarQubeServiceEndpoint}}
        sonarQubeServiceEndpointGeneric: ${{variables.sonarQubeServiceEndpointGeneric}}        
        commandBuild: ${{variables.commandBuild}}
        unitTestCommand: ${{variables.unitTestCommand}}
        appType: ${{variables.appType}}
        versionNode: ${{variables.versionNode}}
        idfluid: ${{variables.idfluid}}
        secretfluid: ${{variables.secretfluid}}
        packageWorkingDir: ${{variables.packageWorkingDir}}
