Description: Diseno de Esquema de Base de Datos, Base de Conocimiento Banistmo (B.O.B)

Parameters:

    Stage:
      Description: dev
      Type: String

    AccountIndicator:
      Description: bob
      Type: String

Conditions:
  AmbientePR: !Equals [ !Ref Stage, "pr" ]
  AmbienteQA: !Equals [ !Ref Stage, "qa" ]
  AmbienteQAE: !Equals [ !Ref Stage, "qae" ]
  AmbienteINT: !Equals [ !Ref Stage, "dev" ]

Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: awsuseast1-${Stage}cpidboingsw-${AccountIndicator}
        AttributeDefinitions:
          - 
            AttributeName: issueId
            AttributeType: S
          - 
            AttributeName: verify
            AttributeType: S
          - 
            AttributeName: solutionId
            AttributeType: S
        KeySchema:
          - 
            AttributeName: issueId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: !If [AmbientePR, True, !If [AmbienteQAE, false, !If [AmbienteQA, false, false]]]
        SSESpecification:
          SSEEnabled: true
        Tags:
          - Key: banistmo:application-code
            Value: BIP-CLD-0331-000-BOB_BCK
          - Key: banistmo:billing-mode
            Value: unico
          - Key: banistmo:pmo-id
            Value: na
          - Key: banistmo:project-name
            Value: Base de Conocimiento Banistmo
          - Key: banistmo:repository
            Value: bipcld0331000-dbn-env-area
          - Key: banistmo:application-cc
            Value: na
          - Key: banistmo:project-cc
            Value: na
        GlobalSecondaryIndexes : [
          {
          IndexName : "verify-index",
          KeySchema : [
            {
              AttributeName : "verify",
              KeyType : "HASH"
            },
          ],                         
          Projection : {
            ProjectionType: "ALL"
          }
        },
        {
          IndexName : "solutionId-index",
          KeySchema : [
            {
              AttributeName : "solutionId",
              KeyType : "HASH"
            },
          ],                         
          Projection : {
            NonKeyAttributes : ["area","environment","solutionUser","solutionTitle", "solutionDetail","solutionAttachment","dateUpdated"],
            ProjectionType: "INCLUDE"
          }
        }]