Description: Diseno de Esquema de Base de Datos, Base de Conocimiento Banistmo (B.O.B)

Parameters:

    Stage:
      Description: desarrollo
      Type: String

    AccountIndicator:
      Description: dev
      Type: String

Conditions:
  AmbientePR: !Equals [ !Ref Stage, "pr" ]
  AmbienteQA: !Equals [ !Ref Stage, "qa" ]
  AmbienteQAE: !Equals [ !Ref Stage, "qae" ]
  AmbienteINT: !Equals [ !Ref Stage, "dev" ]

Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: awsuseast1-devcpidboingsw-bob
        AttributeDefinitions:
          - 
            AttributeName: issueId
            AttributeType: S
          - 
            AttributeName: verify
            AttributeType: S
          - 
            AttributeName: solutionId
            AttributeType: S
        KeySchema:
          - 
            AttributeName: issueId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: !If [AmbientePR, True, !If [AmbienteQAE, false, !If [AmbienteQA, false, false]]]
        SSESpecification:
          SSEEnabled: true
        GlobalSecondaryIndexes : [
          {
          IndexName : "verify-index",
          KeySchema : [
            {
              AttributeName : "verify",
              KeyType : "HASH"
            },
          ],                         
          Projection : {
            ProjectionType: "ALL"
          }
        },
        {
          IndexName : "solutionId-index",
          KeySchema : [
            {
              AttributeName : "solutionId",
              KeyType : "HASH"
            },
          ],                         
          Projection : {
            NonKeyAttributes : ["area","environment","solutionUser","solutionTitle", "solutionDetail","solutionAttachment","dateUpdated"],
            ProjectionType: "INCLUDE"
          }
        }]