Description: Diseno de Esquema de Base de Datos, Base de Conocimiento Banistmo (B.O.B) para el Ambiente y Area de TI

Parameters:

    Stage:
      Description: dev
      Type: String

    AccountIndicator:
      Description: bob
      Type: String

Conditions:
  AmbientePR: !Equals [ !Ref Stage, "pr" ]
  AmbienteQA: !Equals [ !Ref Stage, "qa" ]
  AmbienteQAE: !Equals [ !Ref Stage, "qae" ]
  AmbienteINT: !Equals [ !Ref Stage, "dev" ]

Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: awsuseast1-${Stage}cpidboingsw-env-area-${AccountIndicator}
        AttributeDefinitions:
          - 
            AttributeName: id
            AttributeType: S
          - 
            AttributeName: type
            AttributeType: S
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: !If [AmbientePR, True, !If [AmbienteQAE, false, !If [AmbienteQA, false, false]]]
        SSESpecification:
          SSEEnabled: true
        Tags:
          - Key: banistmo:application-code
            Value: BIP-CLD-0331-000-BOB_BCK
          - Key: banistmo:billing-mode
            Value: unico
          - Key: banistmo:pmo-id
            Value: na
          - Key: banistmo:project-name
            Value: Base de Conocimiento Banistmo
          - Key: banistmo:repository
            Value: bipcld0331000-dbn-bob
          - Key: banistmo:application-cc
            Value: na
          - Key: banistmo:project-cc
            Value: na
        GlobalSecondaryIndexes : [
          {
          IndexName : "type-index",
          KeySchema : [
            {
              AttributeName : "type",
              KeyType : "HASH"
            },
          ],                         
          Projection : {
            NonKeyAttributes : ["name"],
            ProjectionType: "INCLUDE"
          }
        }]