service: ingsw-nestjs-dynamodb-api-rest

plugins:
  - serverless-offline

configValidationMode: warn

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  timeout: 30
  environment: 
    DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodbURL}

functions:
 app: 
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}

custom: 
  endpoints:
    dynamodbURL: 'http://localhost:8000'